### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by salazarr** [kwikteam/klusta#16]
Hi,

I have installed 'klusta' using the following instructions (https://github.com/kwikteam/klusta/#quick-install-guide) on a windows and a mac machine.When I run the command:

klusta params.prm --debug

on one of your examples ('https://github.com/klusta-team/example') I keep getting comparable errors messages from both machines:

 File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/klusta/launch.py", line 334, in main
    return klusta(*args, **kwargs)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/klusta/launch.py", line 182, in klusta
    overwrite=overwrite,
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/klusta/kwik/creator.py", line 395, in create_kwik
    assert 'spikedetekt' in prm

Thanks for your help,

Rodrigo.

**Comment by rossant** [comment]
Hi Rodrigo,

That example repo is outdated and the format of the PRM has slightly changed. I've updated the repo accordingly.

You'll find a [new example in the documentation](http://klusta.readthedocs.org/en/latest/#test-dataset).

**Comment by salazarr** [comment]
Hi Cyrille,

Great! it works nicely.

Best,

R.
On Apr 4, 2016, at 2:30 PM, Cyrille Rossant <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Rodrigo,

That example repo is outdated and the format of the PRM has slightly changed. I've updated the repo accordingly.

You'll find a new example in the documentation<http://klusta.readthedocs.org/en/latest/#test-dataset>.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/kwikteam/klusta/issues/16#issuecomment-205274875>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rodrigo F. Salazar Toro, PhD
University of Geneva
Department of Basic Neuroscience
Rue Michel-Servet 1
CH-1211 Geneva 4
Switzerland
Phone #: +41 (0)22 379 54 69
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by salazarr** [comment]
Hi Cyrille,


Actually it ran fine until calling KlustaKwik. It gave me the following error:


"

...
09:03:32 [I] launch:219           Starting clustering on shank 0/1.
09:03:32 [D] model:661            Enable waveform filter.
09:03:32 [D] model:450            Loading traces: hybrid_10sec.dat
09:03:32 [I] model:1015           Kwik file `F:\salazar\matlab\klustasuite\example-master\hybrid_10sec.kwik` loaded.
09:03:32 [I] launch:222           Clustering group 0 (1653 spikes).
09:03:32 [I] launch:105           Running KK...
Traceback (most recent call last):
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\salazarr\AppData\Local\Continuum\Miniconda3\envs\klusta\Scripts\klusta.exe\__main__.py", line 9, in <module>
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klusta\launch.py", line 334, in main
    return klusta(*args, **kwargs)
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klusta\launch.py", line 226, in klusta
    spike_clusters, metadata = cluster(model)
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klusta\launch.py", line 110, in cluster
    **params)
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klusta\klustakwik.py", line 104, in klustakwik
    data = sparsify_features_masks(features, masks)
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klusta\klustakwik.py", line 21, in sparsify_features_masks
    from klustakwik2 import RawSparseData
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klustakwik2-0.2.4-py2.7-win-amd64.egg\klustakwik2\__init__.py", line 3, in <module>
    from .mask_starts import *
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klustakwik2-0.2.4-py2.7-win-amd64.egg\klustakwik2\mask_starts.py", line 5, in <module>
    from .numerics import mask_start_clusters
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klustakwik2-0.2.4-py2.7-win-amd64.egg\klustakwik2\numerics\__init__.py", line 7, in <module>
    from .cylib import *
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klustakwik2-0.2.4-py2.7-win-amd64.egg\klustakwik2\numerics\cylib\__init__.py", line 4, in <module>
    from .e_step import *
  File "c:\users\salazarr\appdata\local\continuum\miniconda3\envs\klusta\lib\site-packages\klustakwik2-0.2.4-py2.7-win-amd64.egg\klustakwik2\numerics\cylib\e_step.py", line 2, in <module>
    from .e_step_cy import *
ImportError: DLL load failed: The specified module could not be found.


"

Any idea?


Thanks,


ROdrigo.



________________________________
De : Cyrille Rossant <notifications@github.com>
Envoyé : lundi 4 avril 2016 14:30
À : kwikteam/klusta
Cc : Rodrigo Salazar Toro
Objet : Re: [kwikteam/klusta] installation problem (#16)


Hi Rodrigo,

That example repo is outdated and the format of the PRM has slightly changed. I've updated the repo accordingly.

You'll find a new example in the documentation<http://klusta.readthedocs.org/en/latest/#test-dataset>.

-

**Comment by rossant** [comment]
Ah, it means that the compiled klustakwik for Windows doesn't work on your machine... You could try to compile it yourself but it is excessively complicated on Windows :( @nippoo @thesamovar any ideas?

**Comment by salazarr** [comment]
Hi Rossant,

Do you have any guideline on compiling klustakwik on a windows machine so that I can do it myself?

Thanks,

Rodrigo.

**Comment by nippoo** [comment]
Hi Rodrigo,

How did you install KlustaKwik - using the conda package? I'm surprised that doesn't work. What is your OS and hardware specs?

You should be able to do `pip install klustakwik2` to compile yourself but you'll need the appropriate version of Visual Studio installed and the correct environment variables to use that linker and compiler. (I think it's Visual Studio 2010, from memory - and you should probably launch a "Visual Studio 2010 Shell" before activating your environment and doing a `pip install klustakwik2`

Max

**Comment by salazarr** [comment]
Hi Max,


I installed klusta by following the steps described in


https://github.com/kwikteam/klusta/#quick-install-guide


Thus yes using the conda package.


My OS is


Windows Server 2012 R2

64-bit, x64-based processor


Do you need any other info? I have visual studio 2013 already install on the machine. Do I really need 2010?


Thanks,


Rodrigo


 Thus



________________________________
De : Max Hunter <notifications@github.com>
Envoyé : vendredi 8 avril 2016 14:05
À : kwikteam/klusta
Cc : Rodrigo Salazar Toro
Objet : Re: [kwikteam/klusta] installation problem (#16)


Hi Rodrigo,

How did you install KlustaKwik - using the conda package? I'm surprised that doesn't work. What is your OS and hardware specs?

You should be able to do pip install klustakwik2 to compile yourself but you'll need the appropriate version of Visual Studio installed and the correct environment variables to use that linker and compiler. (I think it's Visual Studio 2010, from memory - and you should probably launch a "Visual Studio 2010 Shell" before activating your environment and doing a pip install klustakwik2

Max

-

**Comment by nippoo** [comment]
Hmm, yeah, it might be a WS2012 issue, though I'm surprised if that were the case. I haven't tested it on any Windows Server OSs...

I'm pretty sure you need a specific, older, version of VS to compile Python 2.7 / Cython code (later versions won't do), and it's a right mess, but @thesamovar will be more helpful here...

**Comment by thesamovar** [comment]
For building for Python 2.7 you can use this helpfully provided free download from MS: https://www.microsoft.com/en-us/download/details.aspx?id=44266

If you install Python from the latest Anaconda on Windows this should be bundled with it I believe.
