### ISSUE TITLE
Error in klustaviewa: ShimWarning: The `IPython.qt` package has been deprecated

### ISSUE THREAD

**Issue by salazarr** [kwikteam/klusta#17]
Hi,

I receive this error message when opening klustaviewa:

(klusta)milodon-2:session01 rsalazar$ klustaviewa

/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
<klustaviewa.gui.mainwindow.MainWindow object at 0x10d4989d0>

Any idea?

After the error message, klustaviewa opens but I cannot load any .kwik file. If I run the following command:

klustaviewa 2016030301.kwik 

I get the same error message:

Plus the folowing message in a separate window after klustaviewa is opened:

An error occurred: Traceback (most recent call last):
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/gui/threads.py", line 33, in open
    loader.open(path)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/kwikloader.py", line 120, in open
    self.experiment = Experiment(basename, dir=dir, mode='a')
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/experiment.py", line 403, in __init__
    self.channel_groups = self._gen_children('channel_groups', ChannelGroup)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/experiment.py", line 165, in _gen_children
    for child in container
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/experiment.py", line 440, in __init__
    self.clusters = ClustersNode(self._files, self._node.clusters, root=self._root)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/tables/group.py", line 813, in __getattr__
    return self._f_get_child(name)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/tables/group.py", line 683, in _f_get_child
    self._g_check_has_child(childname)
  File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/tables/group.py", line 407, in _g_check_has_child
    % (self._v_pathname, name))
NoSuchNodeError: group ``/channel_groups/1`` does not have a child named ``clusters``

Thanks,

Rodrigo.

**Comment by rossant** [comment]
Hi,
The first message is not a problem.
Regarding the second message, could you send me your dataset via a file sharing service? Also, what version of the software did you use to create this dataset?

**Comment by salazarr** [comment]
Cyrille,



The problem is similar if I use your example 'hybrid_10sec.kwik'. About the version of klustakwik, it is the one that comes with the installation of klusta as it runs both spikedetect and klustakwik, correct?. Do you have a command to know exactly its version?


Thanks,


Rodrigo.

________________________________
De : Cyrille Rossant <notifications@github.com>
Envoyé : vendredi 8 avril 2016 19:30
À : kwikteam/klusta
Cc : Rodrigo Salazar Toro
Objet : Re: [kwikteam/klusta] Error in klustaviewa: ShimWarning: The `IPython.qt` package has been deprecated (#17)


Hi,
The first message is not a problem.
Regarding the second message, could you send me your dataset via a file sharing service? Also, what version of the software did you use to create this dataset?

-
