### ISSUE TITLE
error running klustaviewa on linux

### ISSUE THREAD

**Issue by salazarr** [kwikteam/klusta#18]
Hi 

I have installed klusta from the web page :

https://github.com/kwikteam/klusta/#quick-install-guide

and tried to open klustaviewa but I get the following error message:

klustaviewa
Traceback (most recent call last):
  File "/home/mint/miniconda3/envs/klusta/bin/klustaviewa", line 7, in <module>
    from klustaviewa.scripts.runklustaviewa import main
  File "/home/mint/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/__init__.py", line 44, in <module>
    from kwiklib.utils import logger as log
  File "/home/mint/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/__init__.py", line 9, in <module>
    import dataio
  File "/home/mint/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/__init__.py", line 4, in <module>
    from kwikloader import *
  File "/home/mint/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/kwikloader.py", line 31, in <module>
    from .experiment import Experiment
  File "/home/mint/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/experiment.py", line 16, in <module>
    from klusta.traces.waveform import WaveformLoader, SpikeLoader
  File "/home/mint/miniconda3/envs/klusta/lib/python2.7/site-packages/klusta/traces/__init__.py", line 9, in <module>
    from .spikedetekt import SpikeDetekt
  File "/home/mint/miniconda3/envs/klusta/lib/python2.7/site-packages/klusta/traces/spikedetekt.py", line 13, in <module>
    from tqdm import tqdm
  File "/home/mint/miniconda3/envs/klusta/lib/python2.7/site-packages/tqdm/__init__.py", line 6, in <module>
    from ._main import main
  File "/home/mint/miniconda3/envs/klusta/lib/python2.7/site-packages/tqdm/_main.py", line 3, in <module>
    from docopt import docopt
ImportError: No module named docopt

Any idea?

Thanks,

Rodrigo.

**Comment by rossant** [comment]
can you try `pip install docopt` in a terminal?

**Comment by salazarr** [comment]
Hi Cyrille,


I ran the command that you suggested and the problem persists:


salazarr@salazarr-Precision-WorkStation-T7500 ~ $ pip install docopt
Requirement already satisfied (use --upgrade to upgrade): docopt in ./miniconda3/lib/python3.5/site-packages
salazarr@salazarr-Precision-WorkStation-T7500 ~ $ source activate klusta
discarding /home/salazarr/miniconda3/bin from PATH
prepending /home/salazarr/miniconda3/envs/klusta/bin to PATH
(klusta)salazarr@salazarr-Precision-WorkStation-T7500 ~ $ klustaviewa
Traceback (most recent call last):
  File "/home/salazarr/miniconda3/envs/klusta/bin/klustaviewa", line 7, in <module>
    from klustaviewa.scripts.runklustaviewa import main
  File "/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/__init__.py", line 44, in <module>
    from kwiklib.utils import logger as log
  File "/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/__init__.py", line 9, in <module>
    import dataio
  File "/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/__init__.py", line 4, in <module>
    from kwikloader import *
  File "/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/kwikloader.py", line 31, in <module>
    from .experiment import Experiment
  File "/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/experiment.py", line 16, in <module>
    from klusta.traces.waveform import WaveformLoader, SpikeLoader
  File "/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/klusta/traces/__init__.py", line 9, in <module>
    from .spikedetekt import SpikeDetekt
  File "/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/klusta/traces/spikedetekt.py", line 13, in <module>
    from tqdm import tqdm
  File "/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/tqdm/__init__.py", line 6, in <module>
    from ._main import main
  File "/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/tqdm/_main.py", line 3, in <module>
    from docopt import docopt
ImportError: No module named docopt


Thanks for your help,


ROdrigo.

________________________________
De : Cyrille Rossant <notifications@github.com>
Envoyé : vendredi 8 avril 2016 19:28
À : kwikteam/klusta
Cc : Rodrigo Salazar Toro
Objet : Re: [kwikteam/klusta] error running klustaviewa on linux (#18)


can you try pip install docopt in a terminal?

-

**Comment by nippoo** [comment]
@salazarr could you instead run it after running `source activate klusta`? This will install `docopt` into the correct virtual environment.

**Comment by salazarr** [comment]
Hi Max,



The problem remains and is similar on my windows, mac and linux machines...


Thanks,


Rodrigo.

________________________________
De : Max Hunter <notifications@github.com>
Envoyé : lundi 11 avril 2016 13:40
À : kwikteam/klusta
Cc : Rodrigo Salazar Toro
Objet : Re: [kwikteam/klusta] error running klustaviewa on linux (#18)


@salazarr<https://github.com/salazarr> could you instead run it after running source activate klusta? This will install docopt into the correct virtual environment.

-

**Comment by rossant** [comment]
could you show us the terminal output? The command should look like this:

```bash
$ source activate klusta
(klusta)$ pip install docopt
(klusta)$ python -c "import klusta" 
```

the last line tests whether the "klusta" package works

**Comment by salazarr** [comment]
Here it is:

milodon-2:~ rsalazar$ source activate klusta
discarding /Users/rsalazar/miniconda3/bin from PATH
prepending /Users/rsalazar/miniconda3/envs/klusta/bin to PATH
(klusta)milodon-2:~ rsalazar$ pip install docopt
Requirement already satisfied (use --upgrade to upgrade): docopt in ./miniconda3/envs/klusta/lib/python2.7/site-packages
(klusta)milodon-2:~ rsalazar$ python -c "import klusta"
(klusta)milodon-2:~ rsalazar$

On Apr 11, 2016, at 2:01 PM, Cyrille Rossant <notifications@github.com<mailto:notifications@github.com>> wrote:


could you show us the terminal output? The command should look like this:

$ source activate klusta
(klusta)$ pip install docopt
(klusta)$ python -c "import klusta"

the last line tests whether the "klusta" package works

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/kwikteam/klusta/issues/18#issuecomment-208309234>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rodrigo F. Salazar Toro, PhD
University of Geneva
Department of Basic Neuroscience
Rue Michel-Servet 1
CH-1211 Geneva 4
Switzerland
Phone #: +41 (0)22 379 54 69
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rossant** [comment]
then do

```bash
(klusta)$ python -c "import klustaviewa"
(klusta)$ klustaviewa
```

**Comment by salazarr** [comment]
Cyrille,


still teh same issue


salazarr@salazarr-Precision-WorkStation-T7500 ~/Downloads $ source activate klusta
discarding /home/salazarr/miniconda3/bin from PATH
prepending /home/salazarr/miniconda3/envs/klusta/bin to PATH
(klusta)salazarr@salazarr-Precision-WorkStation-T7500 ~/Downloads $ pip install docopt
Requirement already satisfied (use --upgrade to upgrade): docopt in /home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages
(klusta)salazarr@salazarr-Precision-WorkStation-T7500 ~/Downloads $ python -c "import klusta"
(klusta)salazarr@salazarr-Precision-WorkStation-T7500 ~/Downloads $ python -c "import klustaviewa"
(klusta)salazarr@salazarr-Precision-WorkStation-T7500 ~/Downloads $ klustaviewa
/home/salazarr/miniconda3/envs/klusta/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
<klustaviewa.gui.mainwindow.MainWindow object at 0x7f4493da2c30>


And I cannot open any .kwik file once klustaviewa is opened.


Thanks again,


Rodrigo

________________________________
De : Cyrille Rossant <notifications@github.com>
Envoyé : lundi 11 avril 2016 19:57
À : kwikteam/klusta
Cc : Rodrigo Salazar Toro
Objet : Re: [kwikteam/klusta] error running klustaviewa on linux (#18)


then do

(klusta)$ python -c "import klustaviewa"
(klusta)$ klustaviewa

-

**Comment by rossant** [comment]
These warnings are all normal. What error message do you get when you try to open a kwik file in KlustaViewa? Have you tried to do `klustaviewa yourfile.kwik` to open directly the file when launching the application?

**Comment by salazarr** [comment]
I cannot open any file. The window browser cannot select any .kwik file.

If I try to run :

source activate klusta
discarding /Users/rsalazar/miniconda3/bin from PATH
prepending /Users/rsalazar/miniconda3/envs/klusta/bin to PATH
(klusta)milodon-2:example-master rsalazar$ klustaviewa hybrid_10sec.kwik
/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)


I get a window with the following errors:

An error occurred: Traceback (most recent call last):
File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/gui/threads.py", line 33, in open
loader.open(path)
File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/kwikloader.py", line 120, in open
self.experiment = Experiment(basename, dir=dir, mode='a')
File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/experiment.py", line 403, in __init__
self.channel_groups = self._gen_children('channel_groups', ChannelGroup)
File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/experiment.py", line 165, in _gen_children
for child in container
File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/kwiklib/dataio/experiment.py", line 440, in __init__
self.clusters = ClustersNode(self._files, self._node.clusters, root=self._root)
File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/tables/group.py", line 813, in __getattr__
return self._f_get_child(name)
File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/tables/group.py", line 683, in _f_get_child
self._g_check_has_child(childname)
File "/Users/rsalazar/miniconda3/envs/klusta/lib/python2.7/site-packages/tables/group.py", line 407, in _g_check_has_child
% (self._v_pathname, name))
NoSuchNodeError: group ``/channel_groups/0`` does not have a child named ``clusters``


AND NOTHING IS BEING DISPLAYED ON THE MAIN WINDOW OF KLUSTAVIEWA.

THANKS,

RODRIGO

On Apr 12, 2016, at 11:47 AM, Cyrille Rossant <notifications@github.com<mailto:notifications@github.com>> wrote:


These warnings are all normal. What error message do you get when you try to open a kwik file in KlustaViewa? Have you tried to do klustaviewa yourfile.kwik to open directly the file when launching the application?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/kwikteam/klusta/issues/18#issuecomment-208821668>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rodrigo F. Salazar Toro, PhD
University of Geneva
Department of Basic Neuroscience
Rue Michel-Servet 1
CH-1211 Geneva 4
Switzerland
Phone #: +41 (0)22 379 54 69
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rossant** [comment]
can you send me your kwik and kwx files?

**Comment by salazarr** [comment]
Here are the files.

I am not sure about the klustakwik executable per_se as the kkwik is run with your klusta fct:

klusta *.prm 

Correct? But I have attached the folder that might contain the klustakwik file and that is in my klusta environment.

Also:

The first time that I installed klusta, both klustakwik and klustaviewa for windows worked and I produced a .kwik file (20150401.kwik with

[2015060401earlier.kwik.zip](https://github.com/kwikteam/klusta/files/217000/2015060401earlier.kwik.zip)
[2015060401later.kwik.zip](https://github.com/kwikteam/klusta/files/217001/2015060401later.kwik.zip)

 subfolder ‘_klustakwik') that is readable by klustaviewa. Unfortunately, I don’t remember the version #. I can only tell you that it involved many steps and dependencies that needed to be satisfied. The version got compromised because we tried to make it usable by several users of the same machine. Anyway, since I reinstalled the klusta environment using your simplified installation (https://github.com/kwikteam/klusta/#quick-install-guide), I cannot open any .kwik file (and subfolder named '.klustakwik2') that has been produced since.


Thanks,

Rodrigo.

**Comment by salazarr** [comment]
Sorry I have just realized that I forgot the kwik folder containing the executable.
[klustakwik2-0.2.4-nppy27_0.zip](https://github.com/kwikteam/klusta/files/217186/klustakwik2-0.2.4-nppy27_0.zip)

**Comment by rossant** [comment]
I cannot reproduce the problem on the *earlier* dataset. Regarding the *later* dataset, it looks like KlustaKwik has not run on it? So KlustaViewa cannot open it.

I would suggest to try running klusta and KlustaViewa on the [test dataset](http://klusta.readthedocs.org/en/latest/) as explained in the instructions.

Something else you can do: [install phy](https://github.com/kwikteam/phy#installation) and use `phy kwik-gui yourfile.kwik` to open the newer GUI instead of KlustaViewa on your file.

**Comment by salazarr** [comment]
Cyrille,

The first one has always worked for me thus you should not have any problem with this one. About the second one, thanks a lot for the info. Kkwik did run on it and did not display any particular error message. I dig into running Kkwik on a Buzsaki64-A64 probe and it seems to me that your Buzsaki64*.prb are not correct about the graph neighbors. I ran klusta again with one *.prm file per shank (inspired from your 1x32_buzsaki.prb) and Kkwik produced a .kwik file that is readable by klustaviewa.

Anyway, for now, I can use your code on our dataset (separately for each shank but that’s OK) and it works very nicely. Good job by the way! It is very nice to have simplified the procedures to this level.

Thanks again for your help and support,

Rodrigo.


On Apr 13, 2016, at 6:27 PM, Cyrille Rossant <notifications@github.com<mailto:notifications@github.com>> wrote:


I cannot reproduce the problem on the earlier dataset. Regarding the later dataset, it looks like KlustaKwik has not run on it? So KlustaViewa cannot open it.

I would suggest to try running klusta and KlustaViewa on the test dataset<http://klusta.readthedocs.org/en/latest/> as explained in the instructions.

Something else you can do: install phy<https://github.com/kwikteam/phy#installation> and use phy kwik-gui yourfile.kwik to open the newer GUI instead of KlustaViewa on your file.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/kwikteam/klusta/issues/18#issuecomment-209531849>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rodrigo F. Salazar Toro, PhD
University of Geneva
Department of Basic Neuroscience
Rue Michel-Servet 1
CH-1211 Geneva 4
Switzerland
Phone #: +41 (0)22 379 54 69
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
