### ISSUE TITLE
issue with klustaviewa

### ISSUE THREAD

**Issue by mpgetz** [kwikteam/klusta#21]
I just installed klusta following the quickstart in the docs, and after downloading the test dataset, running klusta on it, I tried to open up klustaviewa but threw this error:

Traceback (most recent call last):
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/gui/mainwindow.py", line 887, in open_done
    self.taskgraph.update_cluster_view()
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/gui/taskgraph.py", line 75, in <lambda>
    return lambda *args, **kwargs: self.run(('_' + name, args, kwargs))
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/gui/taskgraph.py", line 63, in run
    outputs = self.run_single(action)
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/gui/taskgraph.py", line 52, in run_single
    return getattr(self, method)(*args, **kwargs)
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/gui/taskgraph.py", line 395, in _update_cluster_view
    self.get_view('ClusterView').set_data(**data)
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/views/clusterview.py", line 554, in set_data
    self.model = ClusterViewModel(**kwargs)
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/views/clusterview.py", line 106, in __init__
    self.load(**kwargs)
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/views/clusterview.py", line 146, in load
    parent=self.get_group(select(cluster_groups, clusteridx)))
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/klustaviewa/views/clusterview.py", line 455, in get_group
    (group.groupidx() == groupidx)][0]
  File "/home/---/miniconda3/envs/klusta/lib/python2.7/site-packages/pandas/core/series.py", line 225, in wrapper
    if len(self) != len(other):
TypeError: len() of unsized object
None

Any thoughts?
Thanks, 

M

**Comment by rossant** [comment]
what's the output of `conda list`?

**Comment by mpgetz** [comment]
conda                     3.19.3                   py35_0  
conda-env                 2.4.5                    py35_0  
openssl                   1.0.2g                        0  
pip                       8.1.1                    py35_1  
pycosat                   0.6.1                    py35_0  
pycrypto                  2.6.1                    py35_0  
python                    3.5.1                         0  
pyyaml                    3.11                     py35_1  
readline                  6.2                           2  
requests                  2.9.1                    py35_0  
setuptools                20.3                     py35_0  
sqlite                    3.9.2                         0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.0.5                         1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         0

**Comment by rossant** [comment]
could you do `source activate klusta` first?
